### ISSUE TITLE
Demo example works?

### ISSUE THREAD

**Issue by 7iomka** [nikolay-govorov/logux-vuex#3]
I can't test a example
npm run dev command run only logux server
npm run build make build with error in console: nanoclone is not a function
Help me please)

**Comment by mrdimidium** [comment]
Hey. I know about problems with `nanoclone` package (I use it package for to deep clone objects). Solution will be replace `nanoclone` an another package for to deep clone objects.

I'll do it tomorrow, or you can do it yourself if you have a little time to help me.

**Comment by 7iomka** [comment]
> nanoclone

I'm not in a hurry, I'm looking for a solution for two-way synchronization, and for the time being I'm not sure that this will work for me, since the server on the backend is not on node,js, but on C# :(
But in any case, I would be grateful for the fact that I would look at a working example of how it works)

**Comment by mrdimidium** [comment]
Fixed it in `v0.1.3`
